parameters:
     firebase_fcm_client.class: JP\FirebaseNotificationBundle\Services\FirebaseFCMClient

services:
     firebase_fcm_client:
         class:     "%firebase_fcm_client.class%"
         arguments: ["%jp_firebase_notification.firebase_fcm.server_key%"]
         autowire: true